# Generated by Django 2.1.4 on 2018-12-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee_details',
            name='fee',
            field=models.CharField(max_length=20),
        ),
    ]
